spring:
  rabbitmq:
    username: gridcapa
    password: gridcapa
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        consumeTask-in-0:
          binder: rabbit
          destination: core-valid-run-task
        consumeAutoTask-in-0:
          binder: rabbit
          destination: core-valid-run-task-auto
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
    function:
      definition: consumeTask;consumeAutoTask

core-valid-runner:
  binding:
    destination: core-valid-requests

server:
  port: ${CORE_VALID_ADAPTER_SERVER_PORT:8080}