spring:
  rabbitmq:
    username: gridcapa
    password: gridcapa
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        handleRun-in-0:
          binder: rabbit
          destination: core-valid-run-task
          group: core-valid
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1

core-valid-runner:
  amqp:
    queue-name: core-valid-requests

server:
  port: ${CORE_VALID_ADAPTER_SERVER_PORT:8080}